image: node:16

stages:
  - build
  - test
  - deploy
  - "release"

build:
  stage: build
  script:
    - npm ci
    - npm run build
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/
      - build/

test:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  dependencies:
    - build
  script:
    - npm run test:ci
  cache:
    paths:
      - coverage/
  artifacts:
    paths:
      - coverage/
    when: always
    reports:
      junit:
        - junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

integration-test:
  stage: test
  dependencies:
    - build
  script:
    - npm run test:integration:ci

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mkdir public-tmp
    - cp -r coverage/* public-tmp
    - mv public-tmp public
  artifacts:
    paths:
      - public
  only:
    - master

changelog:
  stage: release
  only:
    - master
  artifacts:
    when: on_success
    paths: ["RELEASE_NOTES.md"]
    reports:
      dotenv: build.env
  cache:
    paths:
      - node_modules/
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GIT_SSH_PRIV_KEY")
    - mkdir -p ~/.ssh
    - ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_NAME}"
  script:
    - git remote rm origin && git remote add origin git@gitlab.com:$CI_PROJECT_PATH.git
    - git pull origin $CI_COMMIT_REF_NAME
    - npm ci
    - |-
      if [ "$RELEASE_AS" != "" ]; then
        npm run version -- --release-as $RELEASE_AS
      else 
        npm run version
      fi
    - echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> build.env
    - git push -o ci.skip origin HEAD:$CI_COMMIT_REF_NAME # Pushes to the same branch as the trigger
    - diff --changed-group-format='%>' --unchanged-group-format='' <( git show HEAD~1:CHANGELOG.md ) CHANGELOG.md > RELEASE_NOTES.md || true

release_job:
  only:
    - master
  needs: ["changelog"]
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo $PACKAGE_VERSION
  release:
    tag_name: $PACKAGE_VERSION
    name: "Release $PACKAGE_VERSION"
    description: RELEASE_NOTES.md

publish:
  only:
    - master
  stage: release
  needs: ["build", "release_job"]
  dependencies:
    - build
  interruptible: false
  retry: 1
  script:
    - npm config set -- '//registry.npmjs.org/:_authToken' "${NPM_AUTH_TOKEN}"
    - ls -l && ls -l build/*
    - npm publish --access public
